### ISSUE TITLE
Todo 1: Create PHP scripting for Database setup

### ISSUE THREAD

**Issue by littleswany** [littleswany/duties-mailer#1]
To create a script that creates the necessary database, and tables for the application. And then create wiki pages on how this works and how to setup.

- [ ] Create database setup script
- [ ] Create table setup script 
- [ ] Test the scripts
- [ ] Create wiki content
