### ISSUE TITLE
Todo 1: Adjust the database schema

### ISSUE THREAD

**Issue by littleswany** [littleswany/duties-mailer#2]
Change the current database schema so it is more organised and coherent to  3rd Normal Form

- [ ] Work out the new database schema
- [ ] Create the necessary SQL files to achieve this
- [ ] Test the SQL files
